[package]
name = "distributed-verification"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[package.metadata.rust-analyzer]
rustc_private = true
