use rustc_middle::ty::TyCtxt;
use rustc_span::source_map::SourceMap;
use serde::Serialize;
use stable_mir::{CrateDef, DefId, mir::mono::Instance};

/// A Rust funtion with its file source, attributes, and raw function content.
#[derive(Debug, Serialize)]
pub struct SerFunction {
    /// DefId in stable_mir.
    def_id: String,
    /// Every funtion must be declared in a specific file, even for those
    /// generated by macros.
    file: String,
    /// Attributes are attached the function, but it seems that attributes
    /// and function must be separated to query.
    attrs: Vec<String>,
    /// Raw function string, including name, signature, and body.
    func: String,
    /// Recursive fnction calls inside the body.
    callees: Vec<Callee>,
}

impl SerFunction {
    pub fn new(fun: super::Function, tcx: TyCtxt, src_map: &SourceMap) -> Self {
        SerFunction {
            def_id: format_def_id(&fun.def_id),
            file: fun.file,
            attrs: fun.attrs.iter().map(|a| a.as_str().to_owned()).collect(),
            func: fun.func,
            callees: fun.callees.iter().map(|x| Callee::new(x, tcx, src_map)).collect(),
        }
    }
}

fn format_def_id(def_id: &DefId) -> String {
    format!("{def_id:?}")
}

#[derive(Debug, Serialize)]
pub struct Callee {
    def_id: String,
    file: String,
    func: String,
}

impl Callee {
    fn new(inst: &Instance, tcx: TyCtxt, src_map: &SourceMap) -> Self {
        let inst_def = &inst.def;
        let def_id = format_def_id(&inst_def.def_id());
        let file = inst_def.span().get_filename();
        let func = inst
            .body()
            .map(|body| super::source_code_with(body.span, tcx, src_map))
            .unwrap_or_default();
        Callee { def_id, file, func }
    }
}
