name: Initialize and Install kani

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    - name: Init Submodules
      run: .github/workflows/init-submodules.sh
      shell: bash

    - name: Install kani
      run: bash ./.github/install-kani.sh
      shell: bash
