name: Generate kani-list

on:
  workflow_call:

jobs:
  gen-kani-list:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Init
        uses: ./.github/actions/init
