name: Verify Kani Harnesses

on:
  workflow_call:
    inputs:
      os:
        description: os that runs-os takes
        type: string

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-24.04-arm, ubuntu-latest]
        partition: [1,2,3,4,5,6,7,8]
    name: ${{ inputs.os }}-partition-${ matrix.partition }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Download kani-list.json
        uses: actions/download-artifact@v4
        with:
          name: kani-list.json-${{ inputs.os }}

      - name: View kani-list
        working-directory: output
        run: |
          ls -alh
          # head -n 100 kani-list.json
          cat partition/${{ matrix.partition }}.json
