name: Run Tests

on:
  push:
    branches: 

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    # runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kani and verify-rust-std
        run: |
          git submodule update --init --recursive verify-rust-std
          ./.github/install-kani.sh

      - name: Install distributed-verification
        run: cargo install --path . --locked

      - name: Verify Rust Std
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.github/gen_core.json.sh

      - name: View core.json
        working-directory: assets/json
        run: |
          ls -alh core.json
          head -n 100 core.json

      - name: Upload core.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-libcore
          path: |
            assets/json
            assets/core.sqlite3
          compression-level: 9
          if-no-files-found: error

      - name: Run tests
        run: cargo test -- --nocapture

  kani-list:
    name: kani-list${{ matrix.autoharness }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        autoharness: ["", "-autoharness"]
    if: true
    env:
      UNSTABLE_ARGS: -Z function-contracts -Z mem-predicates -Z float-lib -Z c-ffi -Z loop-contracts -Z quantifiers -Z stubbing
      AUTO: ${{ matrix.autoharness }}
    steps:
      - name: Remove unnecessary software to free up disk space
        run: |
          # inspired by https://github.com/easimon/maximize-build-space/blob/master/action.yml
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/.ghcup
          df -h

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Kani list
        working-directory: verify-rust-std
        if: ${{ env.AUTO == '' }}
        run:  kani list ${{ env.UNSTABLE_ARGS }} --std ./library --format=json

      - name: Kani list with Autoharness
        working-directory: verify-rust-std
        if: ${{ env.AUTO == '-autoharness' }}
        run: kani autoharness -Z autoharness --list ${{ env.UNSTABLE_ARGS }} --std ./library --format=json

      - name: View list
        working-directory: verify-rust-std
        run: ls -alh kani-list.json && head -n 100 kani-list.json

      - name: Upload kani-list.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-kani-list${{ env.AUTO }}
          path: verify-rust-std/kani-list.json
          compression-level: 9
          if-no-files-found: error

