name: Run Tests

on:
  push:
    branches: 

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Run tests
        run: cargo test -- --nocapture

  verify-rust-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Install distributed-verification
        run: cargo install --path . --locked

      - name: Verify Rust Std
        working-directory: tests/dummy-crate
        env:
          RUST_LOG: off
          CORE_JSON: ${{ github.workspace }}/core.json
          KANI_DIR: ${{ github.workspace }}/kani/target/kani
          VERIFY_RUST_STD_LIBRARY: ${{ github.workspace }}/tests/dummy-crate/verify-rust-std/library
        run: |
          ls -alh ${{ env.VERIFY_RUST_STD_LIBRARY }}
          cargo r --example verify_rust_std
          cat ${{ env.CORE_JSON }}

      - name: Print core.json
        run: |
          ls -alh core.json
          head -n 5000 core.json

      - name: Upload core.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-libcore
          path: core.json
          compression-level: 9
          if-no-files-found: error

  kani-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Kani list
        working-directory: tests/dummy-crate/verify-rust-std
        env:
          UNSTABLE_ARGS: -Z function-contracts -Z mem-predicates -Z float-lib -Z c-ffi -Z loop-contracts
        run: kani list -Zlist ${{ env.UNSTABLE_ARGS }} --std ./library --format=json

      - name: View list
        working-directory: tests/dummy-crate/verify-rust-std
        run: ls -alh kani-list.json && cat kani-list.json

      - name: Upload kani-list.json
        uses: actions/upload-artifact@v4
        with:
          name: artifact-kani-list
          path: ./tests/dummy-crate/verify-rust-std/kani-list.json
          compression-level: 9
          if-no-files-found: error

