name: Verify

on:
  push:

env:
  CARGO_TERM_COLOR: always
  STD_LIBRARY: verify-rust-std/library

jobs:
  verify:
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # - name: Remove unnecessary software to free up disk space
      #   run: |
      #     # inspired by https://github.com/easimon/maximize-build-space/blob/master/action.yml
      #     df -h
      #     sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/.ghcup
      #     df -h

      - name: Install kani
        run: bash ./.github/install-kani.sh

      - name: Run Kani on Autoharness
        working-directory: verify-rust-std
        # This command only takes less than 40s to finish.
        # --include-pattern reduces time by skipping mismatched autoharness, but it still includes contract harnesses.
        # --harness reduces time by running the exact harness verification.
        run: |
          kani autoharness -Z autoharness -Z function-contracts -Z mem-predicates \
            -Z float-lib -Z c-ffi -Z loop-contracts -Z quantifiers -Z stubbing \
            --std ./library -Z unstable-options --harness-timeout 10m --default-unwind 1000 \
            --include-pattern intrinsics::verify::should_succeed_i32_to_u32 \
            --harness intrinsics::verify::should_succeed_i32_to_u32 

      - name: Install verify_rust_std
        run: cargo install --path . --locked --debug

      - name: verify_rust_std kani-run
        # This should takes the same verification time as the kani cmd above.
        run: verify_rust_std kani-run intrinsics::verify::should_succeed_i32_to_u32

      - name: verify_rust_std kani-list
        # This should takes the same verification time as `kani autoharness --list`.
        # run: verify_rust_std kani-list
        run: cp assets/kani-list_vrs.json kani-list.json # local kani-list.json

      - name: View kani-list.json
        run: ls -alh kani-list.json && head -n 100 kani-list.json

      - name: Generate assets/json
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./.github/gen_core.json.sh

      - name: Generate hash.json
        run: |
          export PREFIX_CI=$PWD/verify-rust-std/library/
          export PREFIX_LOCAL=/home/gh-zjp-CN/distributed-verification/verify-rust-std/library/
          verify_rust_std merge --hash-json assets/json/ --kani-list kani-list.json \
            --strip-hash-json-prefix $PREFIX_CI \
            --strip-kani-list-prefix $PREFIX_LOCAL > hash.json

      - name: Generate Diff Result
        # FIXME: currently there is no old hash.json.
        run: verify_rust_std diff --old hash.json --new hash.json | tee diff.json 

      - name: Verify Diff Result
        run: verify_rust_std kani-run $(jq -r 'map(.func) | join(" ")' diff.json)

      - name: Upload JSONs
        uses: actions/upload-artifact@v4
        with:
          name: verify-${{ matrix.os }}
          path: kani-list.json hash.json diff.json
          compression-level: 9
          if-no-files-found: error

